version: '3.1'

services:
  proxy:
    image: nginx:alpine
    ports: 
      - 5001:80
    volumes: 
      - wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    links: 
      - wordpress

  wordpress:
    image: wordpress:php7.2-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: shopdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    ports: 
      - 3308:3306
    environment:
      MYSQL_DATABASE: shopdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: