version: '3.6'

services:
  proxy:
    image: wpapi-proxy
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # - ./ssl:/etc/ssl
      - wordpress:/var/www/html/wpapi
    links: 
      - wordpress
    networks: 
      wpapi_network:
        ipv4_address: 10.0.0.2

  wordpress:
    image: wordpress:php7.2-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: shopdb
    volumes:
      - wordpress:/var/www/html/wpapi
    networks: 
      wpapi_network:
        ipv4_address: 10.0.0.3

  db:
    image: mysql:5.7
    ports: 
      - 3308:3306
    environment:
      MYSQL_DATABASE: shopdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - db:/var/lib/mysql
    networks: 
      wpapi_network:
        ipv4_address: 10.0.0.4

volumes:
  wordpress:
  db:

networks:
  wpapi_network:
    ipam:
      driver: default
      config: 
        - subnet: 10.0.0.0/24