version: '3.1'

services:
  proxy:
    image: nginx:alpine
    expose: 
      - 80
      - 443
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - wordpress:/var/www/html/wpapi
    links: 
      - wordpress
    networks: 
      wpapi_network:
        ipv4_address: 172.28.0.250

  wordpress:
    image: wordpress:php7.2-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: shopdb
    volumes:
      - wordpress:/var/www/html
    networks: 
      wpapi_network:
        ipv4_address: 172.28.0.251

  db:
    image: mysql:5.7
    expose: 
      - 3306
    environment:
      MYSQL_DATABASE: shopdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - db:/var/lib/mysql
    networks: 
      wpapi_network:
        ipv4_address: 172.28.0.252

volumes:
  wordpress:
  db:

networks:
  wpapi_network:
    ipam:
      driver: default
      config: 
        - subnet: 172.28.0.0/16