FROM nginx:alpine

RUN apk add --no-cache openssl \
    && openssl req -x509 \ 
        -nodes \ 
        -days 365 \ 
        -subj "/C=TH/ST=BKK/O=Agentone co, ltd./CN=localhost" \ 
        -addext "subjectAltName=DNS:localhost" \ 
        -newkey rsa:2048 \ 
        -keyout /etc/ssl/private/localhost.key \ 
        -out /etc/ssl/certs/localhost.crt;
